(function(){
const A=[
['profile-created','🌱','First Steps','Profile','Common','Create a community profile.',c=>1,1],
['profile-name','🪪','Known by Name','Profile','Common','Add a public profile name.',c=>c.profileName?1:0,1],
['bio-added','📖','Storyteller','Profile','Common','Write a profile biography.',c=>c.bioLen,40],
['bio-master','📚','Detailed Adventurer','Profile','Rare','Write a biography with at least 180 characters.',c=>c.bioLen,180],
['status-added','💬','Status Set','Profile','Common','Add a custom status.',c=>c.status?1:0,1],
['location-added','🧭','On the Map','Profile','Common','Share a profile location.',c=>c.location?1:0,1],
['mode-added','⚔️','Choose Your Path','Profile','Common','Choose a favorite game mode.',c=>c.favoriteMode?1:0,1],
['profile-image','🖼️','Picture Perfect','Profile','Uncommon','Upload a profile image.',c=>c.profileImage?1:0,1],
['signature-text','✒️','Signed & Sealed','Profile','Common','Create a forum signature.',c=>c.signatureText?1:0,1],
['signature-image','🎨','Signature Artist','Profile','Rare','Upload a signature image.',c=>c.signatureImage?1:0,1],
['profile-complete','💯','Complete Identity','Profile','Epic','Complete the main profile fields.',c=>c.profileComplete,7],
['minecraft-linked','🟩','Minecraft Linked','Minecraft','Common','Link a Java Minecraft profile.',c=>c.linked?1:0,1],
['minecraft-profile','⛏️','Blocky Identity','Minecraft','Uncommon','Link Minecraft and add a profile image.',c=>(c.linked&&c.profileImage)?1:0,1],
['first-topic','📝','Forum Starter','Topics','Common','Create your first forum topic.',c=>c.posts,1],
['topics-5','📌','Topic Maker','Topics','Uncommon','Create 5 forum topics.',c=>c.posts,5],
['topics-10','🗂️','Discussion Architect','Topics','Rare','Create 10 forum topics.',c=>c.posts,10],
['topics-25','📣','Community Broadcaster','Topics','Epic','Create 25 forum topics.',c=>c.posts,25],
['topics-50','👑','Forum Publisher','Topics','Legendary','Create 50 forum topics.',c=>c.posts,50],
['first-reply','💬','Joined the Conversation','Replies','Common','Post your first forum reply.',c=>c.replies,1],
['replies-10','🧵','Conversation Crafter','Replies','Uncommon','Post 10 forum replies.',c=>c.replies,10],
['replies-25','🗣️','Active Voice','Replies','Rare','Post 25 forum replies.',c=>c.replies,25],
['replies-50','📢','Community Conversationalist','Replies','Epic','Post 50 forum replies.',c=>c.replies,50],
['replies-100','🏆','Century Speaker','Replies','Legendary','Post 100 forum replies.',c=>c.replies,100],
['activity-10','🔥','Getting Active','Activity','Common','Reach 10 total forum activities.',c=>c.total,10],
['activity-50','⚡','Forum Regular','Activity','Rare','Reach 50 total forum activities.',c=>c.total,50],
['activity-100','🌟','Community Pillar','Activity','Epic','Reach 100 total forum activities.',c=>c.total,100],
['reaction-1','❤️','First Applause','Reactions','Common','Receive your first reaction.',c=>c.reactions,1],
['reaction-5','👍','Well Received','Reactions','Common','Receive 5 reactions.',c=>c.reactions,5],
['reaction-10','✨','Rising Reputation','Reactions','Uncommon','Receive 10 reactions.',c=>c.reactions,10],
['reaction-25','💚','Community Favorite','Reactions','Rare','Receive 25 reactions.',c=>c.reactions,25],
['reaction-50','💎','Highly Respected','Reactions','Epic','Receive 50 reactions.',c=>c.reactions,50],
['reaction-100','🌠','Reaction Legend','Reactions','Legendary','Receive 100 reactions.',c=>c.reactions,100],
['reaction-250','👑','Community Icon','Reactions','Mythic','Receive 250 reactions.',c=>c.reactions,250],
['views-25','👀','Getting Noticed','Views','Common','Earn 25 views across your topics.',c=>c.views,25],
['views-100','🔭','Popular Discussions','Views','Uncommon','Earn 100 topic views.',c=>c.views,100],
['views-500','📡','Forum Spotlight','Views','Rare','Earn 500 topic views.',c=>c.views,500],
['views-1000','🌐','Viral Crafter','Views','Legendary','Earn 1,000 topic views.',c=>c.views,1000],
['gallery-1','🧱','Build Showcase','Gallery','Common','Upload your first build.',c=>c.gallery,1],
['gallery-3','🏠','Creative Portfolio','Gallery','Uncommon','Upload 3 gallery builds.',c=>c.gallery,3],
['gallery-5','🏰','Master Builder','Gallery','Rare','Upload 5 gallery builds.',c=>c.gallery,5],
['gallery-8','🌆','Gallery Architect','Gallery','Epic','Fill all 8 gallery slots.',c=>c.gallery,8],
['link-1','🔗','Connected','Social','Common','Add one public community link.',c=>c.links,1],
['link-3','🧭','Connected Explorer','Social','Uncommon','Add three public links.',c=>c.links,3],
['link-5','🌍','Everywhere Online','Social','Rare','Add five public links.',c=>c.links,5],
['youtube','▶️','Content Creator','Social','Uncommon','Add a YouTube channel.',c=>c.youtube?1:0,1],
['planetmc','🪐','Planet Minecrafter','Social','Uncommon','Add a Planet Minecraft profile.',c=>c.planetMinecraft?1:0,1],
['discord','🎧','Discord Connected','Social','Common','Add a Discord link.',c=>c.discord?1:0,1],
['twitch','🟣','Live Crafter','Social','Uncommon','Add a Twitch channel.',c=>c.twitch?1:0,1],
['joined','📅','Official Member','Longevity','Common','Have a recorded join date.',c=>c.joined?1:0,1],
['member-7','🕯️','One Week Strong','Longevity','Common','Be a member for 7 days.',c=>c.days,7],
['member-30','🗓️','Monthly Member','Longevity','Uncommon','Be a member for 30 days.',c=>c.days,30],
['member-90','🌳','Established Member','Longevity','Rare','Be a member for 90 days.',c=>c.days,90],
['member-180','🏛️','Community Veteran','Longevity','Epic','Be a member for 180 days.',c=>c.days,180],
['member-365','🎂','One Year Anniversary','Longevity','Legendary','Be a member for 365 days.',c=>c.days,365],
['role-builder','🧱','Official Builder','Special','Rare','Hold the Builder role.',c=>c.role==='Builder'?1:0,1],
['role-donator','💰','Server Supporter','Special','Rare','Hold the Donator role.',c=>c.role==='Donator'?1:0,1],
['role-veteran','🛡️','Veteran Rank','Special','Epic','Hold the Veteran role.',c=>c.role==='Veteran'?1:0,1],
['role-staff','⚖️','Community Staff','Special','Epic','Become a Moderator or Administrator.',c=>['Moderator','Administrator'].includes(c.role)?1:0,1],
['role-founder','👑','Founder','Special','Mythic','Hold the Founder role.',c=>c.role==='Founder'?1:0,1],
['all-rounder','🌈','Community All-Rounder','Special','Legendary','Create topics, reply, earn reactions, upload builds, and add links.',c=>[c.posts>=5,c.replies>=10,c.reactions>=10,c.gallery>=3,c.links>=2].filter(Boolean).length,5]
];
function topics(){try{return JSON.parse(localStorage.getItem('ac_topics')||'[]')}catch{return[]}}
function stats(name){const key=String(name||'').toLowerCase();let posts=0,replies=0,reactions=0,views=0;topics().forEach(t=>{if(String(t.author||'').toLowerCase()===key){posts++;views+=Number(t.views||0)}(t.replies||[]).forEach(r=>{if(String(r.author||'').toLowerCase()===key){replies++;reactions+=Number(r.reaction||r.reactions||0)}})});return{posts,replies,reactions,views,total:posts+replies}}
function dateDays(v){if(!v||v==='Unknown')return 0;const d=new Date(v);return isNaN(d)?0:Math.max(0,Math.floor((Date.now()-d.getTime())/86400000))}
function context(user,p){const s=stats(user.username), links=[p.website,p.planetMinecraft,p.youtube,p.discordLink,p.twitch,p.github].filter(Boolean).length;return{...s,gallery:(p.gallery||[]).length,links,linked:Boolean(user.minecraft&&user.minecraft.username),joined:Boolean(user.joined&&user.joined!=='Unknown'),days:dateDays(user.joined),role:user.role||'Member',profileName:p.profileName,bioLen:(p.bio||'').trim().length,status:p.status,location:p.location,favoriteMode:p.favoriteMode,profileImage:p.profileImage,signatureText:p.signatureText,signatureImage:p.signatureImage,youtube:p.youtube,planetMinecraft:p.planetMinecraft,discord:p.discordLink,twitch:p.twitch,profileComplete:[p.profileName,p.bio,p.status,p.location,p.favoriteMode,user.minecraft&&user.minecraft.username,p.profileImage].filter(Boolean).length}}
function evaluate(user,p){const c=context(user,p);return A.map(x=>{const current=Math.max(0,Number(x[6](c))||0),goal=x[7];return{id:x[0],icon:x[1],name:x[2],category:x[3],rarity:x[4],description:x[5],current,goal,earned:current>=goal,percent:Math.min(100,Math.round(current/goal*100))}})}
window.AetherAchievements={definitions:A,evaluate,context,stats};
})();