function b(x,y,z,t='stone'){return{x,y,z,t}}
function boxBuild(w,d,h,style='stone',roof=true){let L=[];for(let y=0;y<h;y++){let a=[];for(let x=0;x<w;x++)for(let z=0;z<d;z++){let edge=x===0||x===w-1||z===0||z===d-1;if(y===0)a.push(b(x,y,z,style));else if(y<h-2&&edge){let corner=(x===0||x===w-1)&&(z===0||z===d-1);a.push(b(x,y,z,corner?'wood':style))}else if(roof&&y>=h-2){let inset=y-(h-2);if((z===inset||z===d-1-inset)&&x>=0&&x<w)a.push(b(x,y,z,'roof'))}}L.push({name:y===0?'Foundation':y<h-2?'Walls & frame':'Roof & cap',note:y===0?'Mark the footprint and entrances before building upward.':y<h-2?'Raise the shell evenly and leave openings for doors and windows.':'Finish the silhouette, then add stairs, slabs and trim.',blocks:a})}return L}
function towerBuild(w,d,h){let L=[];for(let y=0;y<h;y++){let a=[];for(let x=0;x<w;x++)for(let z=0;z<d;z++){let edge=x===0||x===w-1||z===0||z===d-1;if(y===0||((y<h-2)&&edge)||((y===h-2)&&(x===0||x===w-1||z===0||z===d-1))||((y===h-1)&&edge&&(x%2===0||z%2===0)))a.push(b(x,y,z,y>h-3?'slab':'stone'))}L.push({name:y===0?'Foundation':y<h-2?'Tower shaft':'Battlements',note:'Keep the footprint square and check symmetry from every side.',blocks:a})}return L}
function flatBuild(w,d,h=3,style='wood'){let L=[];for(let y=0;y<h;y++){let a=[];for(let x=0;x<w;x++)for(let z=0;z<d;z++){if(y===0||y===h-1||x===0||x===w-1||z===0||z===d-1){if((x+z+y)%3!==1||y===0)a.push(b(x,y,z,style))}}L.push({name:y===0?'Footprint':y===h-1?'Finish & detail':'Structure',note:'Use this layer as a guide, then vary blocks and add decorative depth.',blocks:a})}return L}
function bridgeBuild(w,d,h){let L=[];for(let y=0;y<h;y++){let a=[];for(let x=0;x<w;x++)for(let z=0;z<d;z++){let center=(w-1)/2,arch=Math.abs(x-center),deck=y===h-2&&z>0&&z<d-1,rail=y===h-1&&(z===1||z===d-2),support=y<h-2&&(x<3||x>w-4)&&z>0&&z<d-1,curve=y===Math.max(0,h-3-Math.floor(arch/3))&&(z===1||z===d-2);if(deck||rail||support||curve)a.push(b(x,y,z,'stone'))}L.push({name:y<h-2?'Arch & supports':'Deck & rails',note:'Mirror placements from the center and adapt supports to your terrain.',blocks:a})}return L}
const CATALOG=[
['castle','Grand Medieval Castle','Castle','Advanced',[25,21,14],'A full keep with four corner towers, courtyard, battlements and layered defenses.','castle medieval keep battlement courtyard fortress'],
['gatehouse','Castle Gatehouse & Portcullis','Castle','Advanced',[15,11,10],'Twin defensive towers surrounding a central gate and portcullis.','castle gate portcullis defense medieval'],
['castle-wall','Castle Wall Segment','Castle','Intermediate',[17,5,8],'Repeatable defensive wall with walkway, crenellations and arrow slits.','wall castle battlement defense'],
['round-tower','Castle Watchtower','Tower','Intermediate',[11,11,14],'Tall defensive tower for walls, villages and hilltop forts.','tower castle watch medieval'],
['wizard-tower','Fantasy Wizard Tower','Fantasy','Advanced',[13,13,18],'A tall fantasy tower with a dramatic roof and magical detailing.','wizard magic fantasy tower'],
['starter-house','Survival Starter House','House','Beginner',[11,9,7],'Compact starter home with framed walls, roof and useful interior space.','house starter survival cottage'],
['medieval-house','Medieval Timber House','House','Intermediate',[13,11,10],'Timber-frame home with stone base, upper overhang and steep roof.','house medieval timber tudor'],
['modern-house','Modern Survival House','House','Intermediate',[15,11,7],'Clean modern home with glass walls, terraces and simple geometry.','modern house quartz glass'],
['cottage','Cozy Forest Cottage','House','Beginner',[11,9,7],'Small rustic cottage suited to forests and village edges.','cottage forest rustic cozy'],
['farmhouse','Large Farmhouse','House','Intermediate',[17,13,9],'Country farmhouse with porch, chimney and practical survival rooms.','farmhouse country porch house'],
['mansion','Woodland Mansion Inspired Home','House','Advanced',[23,19,12],'Large dark-oak manor with multiple wings and layered rooflines.','mansion manor dark oak house'],
['treehouse','Giant Treehouse','Fantasy','Advanced',[17,17,16],'Elevated wooden home wrapped around a custom tree trunk.','tree treehouse fantasy forest'],
['hobbit','Hillside Burrow','Fantasy','Intermediate',[13,9,6],'Earth-sheltered fantasy home with rounded facade and garden roof.','hobbit burrow hillside fantasy'],
['bridge-stone','Medieval Stone Bridge','Infrastructure','Intermediate',[17,7,6],'Arched stone bridge with rails, supports and lantern posts.','bridge stone medieval road'],
['bridge-wood','Rustic Wooden Bridge','Infrastructure','Beginner',[13,5,4],'Simple curved wooden footbridge for rivers and gardens.','bridge wood rustic river'],
['road','Medieval Road & Path','Infrastructure','Beginner',[15,7,2],'Layered path palette using stone, gravel, dirt and roadside details.','road path medieval gravel decoration'],
['harbor','Harbor Dock','Infrastructure','Intermediate',[17,11,5],'Working-looking dock with piers, cranes, barrels and mooring posts.','dock harbor port ship ocean'],
['windmill','Working-Style Windmill','Infrastructure','Intermediate',[11,11,14],'Classic windmill shell with large blades and milling interior.','windmill farm medieval'],
['lighthouse','Coastal Lighthouse','Tower','Intermediate',[11,11,17],'Tall lighthouse with lantern room and coastal foundation.','lighthouse tower coast ocean'],
['barn','Large Survival Barn','Farm','Intermediate',[17,13,10],'Barn for animals, hay storage and farming supplies.','barn farm animals storage'],
['cropfarm','Decorative Crop Farm','Farm','Beginner',[15,13,3],'Organized crop plots with water, paths, scarecrow and borders.','farm crops wheat carrot potato decoration'],
['greenhouse','Glass Greenhouse','Farm','Intermediate',[13,9,7],'Glass growing house for crops, bees and decorative plants.','greenhouse farm glass plants'],
['stable','Horse Stable','Farm','Beginner',[13,9,6],'Stable with individual stalls, hay loft and fenced paddock.','stable horse farm barn'],
['fountain','Village Fountain','Decoration','Beginner',[9,9,5],'Stone centerpiece with water basin, trim and lantern accents.','fountain decoration village water'],
['garden','Fantasy Garden','Decoration','Beginner',[13,11,4],'Layered garden with paths, flower beds, pond and seating.','garden flowers landscaping decoration'],
['market','Market Stall Set','Decoration','Beginner',[9,7,5],'Colorful merchant stalls with awnings, crates and counters.','market stall decoration village shop'],
['streetlamp','Medieval Streetlamp','Decoration','Beginner',[5,5,6],'Compact lamp-post tutorial for roads, towns and castle courtyards.','lamp lantern decoration street'],
['statue','Knight Statue','Decoration','Intermediate',[9,7,13],'Block-built armored knight monument for plazas and castles.','statue knight monument decoration'],
['throne','Royal Throne Room','Interior','Intermediate',[15,11,7],'Interior layout with throne platform, columns, banners and lighting.','interior throne castle decoration'],
['kitchen','Medieval Kitchen','Interior','Beginner',[11,9,5],'Kitchen detailing with hearth, counters, shelves and food storage.','interior kitchen medieval decoration'],
['bedroom','Cozy Bedroom','Interior','Beginner',[9,7,5],'Detailed bedroom with bed frame, storage, desk and lighting.','interior bedroom furniture decoration'],
['library','Enchanting Library','Interior','Intermediate',[13,9,7],'Tall library with enchanting area, shelves and reading alcoves.','library enchanting interior books'],
['storage','Survival Storage Room','Interior','Beginner',[13,9,5],'Organized storage hall with labeled sections and crafting stations.','storage interior survival chest'],
['netherhub','Nether Hub','Nether','Advanced',[21,21,9],'Large symmetrical Nether transport hub with protected corridors.','nether hub portal travel'],
['netherportal','Custom Nether Portal','Nether','Beginner',[9,7,8],'Decorative portal frame with ruined-stone and lava accents.','nether portal decoration'],
['endtower','End Observatory','Fantasy','Advanced',[15,15,14],'End-themed tower using dark blocks, purple glass and floating details.','end fantasy tower purpur'],
['mine','Mine Entrance','Survival','Beginner',[11,7,6],'Detailed mine entrance with supports, rails and storage.','mine entrance survival cave'],
['warehouse','Bulk Storage Warehouse','Survival','Intermediate',[17,13,8],'Large survival warehouse designed around organized storage aisles.','storage warehouse survival'],
['wallmap','Map Room','Interior','Intermediate',[13,11,6],'Exploration room with map wall, planning table and trophy displays.','map room interior exploration'],
['portalroom','Portal Room','Interior','Intermediate',[13,11,7],'Dedicated Nether portal chamber with dramatic framing and lighting.','portal room interior nether'],
['waterfall','Custom Waterfall','Landscaping','Beginner',[13,9,8],'Natural-looking waterfall with rock shaping, pools and vegetation.','waterfall terrain landscaping water'],
['mountain','Custom Mountain','Landscaping','Advanced',[21,17,14],'Layered terrain method for convincing cliffs, slopes and peaks.','mountain terrain landscaping cliff'],
['customtree','Custom Oak Tree','Landscaping','Intermediate',[13,13,14],'Organic trunk and canopy technique for custom forests.','tree landscaping custom nature'],
['pond','Natural Pond','Landscaping','Beginner',[13,11,4],'Small landscaped pond with depth variation and shoreline plants.','pond water landscaping nature'],
['ruins','Ancient Ruins','Landscaping','Intermediate',[15,13,7],'Broken walls, collapsed arches and overgrowth for environmental storytelling.','ruins ancient landscaping decoration'],
['redstone-door','Hidden Piston Door Shell','Redstone','Intermediate',[9,5,6],'Build-friendly facade and cavity plan for a compact hidden entrance.','redstone piston door secret'],
['item-sorter','Item Sorter Housing','Redstone','Intermediate',[13,9,6],'Organized exterior and service corridor for a modular item sorter.','redstone sorter storage automation'],
['super-smelter','Super Smelter Building','Redstone','Advanced',[17,11,7],'Industrial shell designed around furnace arrays and item transport.','redstone smelter automation furnace'],
['mobfarm','Mob Farm Exterior','Farm','Advanced',[17,17,18],'Build shell and tower layout for disguising a hostile-mob farm.','mob farm survival automation'],
['ironfarm','Iron Farm Village Shell','Farm','Advanced',[17,15,10],'Decorative village-inspired housing around an iron farm footprint.','iron farm automation village'],
['bee','Bee Sanctuary','Farm','Beginner',[13,11,6],'Flower-rich apiary with hives, greenhouse details and paths.','bee honey farm flowers'],
['ship','Medieval Sailing Ship','Vehicle','Advanced',[25,9,17],'Layered hull, decks, masts and sails for a large sailing vessel.','ship boat medieval ocean'],
['airship','Fantasy Airship','Vehicle','Advanced',[21,11,15],'Steampunk-inspired flying vessel with balloon frame and gondola.','airship fantasy steampunk vehicle'],
['wagon','Medieval Wagon','Vehicle','Beginner',[9,5,5],'Small wagon for roads, farms and market scenes.','wagon cart medieval decoration'],
['dragon','Block Dragon Statue','Pixel Art','Advanced',[19,13,15],'Large dragon sculpture using silhouette-first organic shaping.','dragon statue pixel art fantasy'],
['logo','Pixel Art Logo Board','Pixel Art','Beginner',[17,3,12],'Grid-based method for converting simple logos into block art.','pixel art logo mural'],
['arena','PvP Arena','Community','Advanced',[25,21,10],'Symmetrical combat arena with stands, entrances and spectator zones.','arena pvp community stadium'],
['spawn','Server Spawn Plaza','Community','Advanced',[27,27,12],'Central multiplayer spawn with portals, paths, information boards and landmarks.','spawn server community hub'],
['shop','Player Shop','Community','Beginner',[11,9,7],'Compact storefront for survival servers and marketplace districts.','shop store market community'],
['portalhub','Portal Hub','Community','Advanced',[23,23,10],'Large multi-portal hub organized around a central landmark.','portal hub server travel community']
];
function chooseLayers(r){let [w,d,h]=r[4],cat=r[2];if(cat==='Tower')return towerBuild(w,d,h);if(cat==='Infrastructure'&&r[0].includes('bridge'))return bridgeBuild(w,d,h);if(['Decoration','Interior','Landscaping','Pixel Art','Vehicle','Redstone'].includes(cat))return flatBuild(w,d,Math.min(h,7),cat==='Interior'?'plank':cat==='Landscaping'?'stone':'wood');return boxBuild(w,d,h,cat==='House'?'plank':'stone',!['Farm','Community'].includes(cat))}
const BUILDS=CATALOG.map(r=>({id:r[0],title:r[1],category:r[2],difficulty:r[3],size:r[4],desc:r[5],tags:r[6].split(' '),materials:materialsFor(r[2]),tips:tipsFor(r[2]),layers:chooseLayers(r)}));
function materialsFor(cat){const common=[['Stone / foundation blocks',160],['Primary building blocks',240],['Stairs & slabs',96],['Detail blocks',64],['Lanterns / lighting',12]];const m={House:[['Logs',96],['Planks',260],['Stone',140],['Stairs',160],['Glass Panes',32],['Lanterns',12]],Decoration:[['Primary blocks',72],['Slabs & stairs',48],['Trapdoors / signs',24],['Lighting',8]],Landscaping:[['Stone',180],['Dirt / grass',220],['Leaves',120],['Logs',48],['Flowers / plants',64]],Interior:[['Planks',140],['Stairs / slabs',72],['Trapdoors',32],['Barrels / chests',18],['Lighting',12]],Farm:[['Building blocks',180],['Fences',80],['Slabs',48],['Lighting',16],['Farm-specific blocks',64]],Redstone:[['Building blocks',160],['Redstone dust',48],['Repeaters / comparators',20],['Pistons / observers',24],['Hoppers',24]]};return m[cat]||common}
function tipsFor(cat){const base=['Build the main silhouette before spending time on tiny details.','Use temporary blocks to mark the center line and major corners.','Mix block variants in small amounts to avoid flat-looking walls.','Walk around the build often and check it from player eye level.'];const extra={Castle:'Use towers and wall depth to create a believable defensive structure.',Decoration:'Small asymmetry usually makes decorative builds feel more natural.',Landscaping:'Avoid perfect circles and straight terrain edges; vary height gradually.',Interior:'Leave walking space first, then add furniture around the movement path.',Redstone:'Test the mechanism in a creative copy before enclosing it in decoration.',Farm:'Confirm the farm mechanics for your exact Minecraft edition/version before decorating it.'};return [...base,extra[cat]||'Adapt the palette to the biome and materials available on your world.']}
const colors={stone:'#778079',wood:'#5d3b24',plank:'#a87949',roof:'#4a2d1c',iron:'#b8c1c1',slab:'#89908b'};let current=BUILDS[0],layer=0,rotX=-.55,rotY=.72,zoom=1,drag=false,last=[0,0];
function init(){populateFilters();renderStats();renderList();selectBuild(current.id);bind();converterExample();}
function populateFilters(){[...new Set(BUILDS.map(x=>x.category))].forEach(c=>$('#buildCategory').insertAdjacentHTML('beforeend',`<option>${c}</option>`))}
function renderStats(){let el=$('#academyStats');if(!el)return;let cats=new Set(BUILDS.map(x=>x.category));el.innerHTML=`<div class="academy-stat"><strong>${BUILDS.length}</strong><span>built-in tutorials</span></div><div class="academy-stat"><strong>${cats.size}</strong><span>build categories</span></div><div class="academy-stat"><strong>${BUILDS.reduce((n,x)=>n+x.layers.length,0)}</strong><span>guided layers</span></div><div class="academy-stat"><strong>Java + Bedrock</strong><span>planning support</span></div>`}function renderList(){let q=$('#buildSearch').value.toLowerCase().trim(),cat=$('#buildCategory').value,d=$('#buildDifficulty').value;let rows=BUILDS.filter(x=>(cat==='all'||x.category===cat)&&(d==='all'||x.difficulty===d)&&(`${x.title} ${x.category} ${x.desc} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(q)));$('#buildList').innerHTML=rows.map(x=>`<button class="academy-build-card ${x.id===current?.id?'active':''}" data-build="${x.id}"><span>${x.category} • ${x.difficulty}</span><strong>${x.title}</strong><small>${x.size.join(' × ')}</small><em>${(x.tags||[]).slice(0,4).join(' • ')}</em></button>`).join('')||`<div class="academy-empty"><strong>No built-in tutorial found.</strong><p>Try a broader term or use the external tutorial searches below.</p></div>`}
function selectBuild(id){current=BUILDS.find(x=>x.id===id)||BUILDS[0];layer=0;$('#buildIntro').hidden=true;$('#buildWorkspace').hidden=false;$('#buildMeta').textContent=`${current.category} • ${current.difficulty}`;$('#buildTitle').textContent=current.title;$('#buildDescription').textContent=current.desc;$('#buildDimensions').innerHTML=`<strong>${current.size.join(' × ')}</strong><span>blocks wide × deep × high</span>`;$('#layerRange').max=current.layers.length-1;$('#layerRange').value=0;$('#materialsGrid').innerHTML=current.materials.map(m=>`<div><strong>${m[1]}</strong><span>${m[0]}</span></div>`).join('');$('#tipsContent').innerHTML=`<ol class="build-tip-list">${current.tips.map(t=>`<li>${t}</li>`).join('')}</ol><div class="academy-tags">${(current.tags||[]).map(t=>`<span class="academy-tag">${t}</span>`).join('')}</div><div class="academy-resources"><a class="academy-resource" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${encodeURIComponent('Minecraft '+current.title+' tutorial')}"><strong>Search video tutorials ↗</strong><span>Find additional visual references for this build.</span></a><a class="academy-resource" target="_blank" rel="noopener" href="https://www.planetminecraft.com/projects/?keywords=${encodeURIComponent(current.title)}"><strong>Search Planet Minecraft ↗</strong><span>Browse related community builds and inspiration.</span></a></div><div class="notice"><strong>Creative tip:</strong> Use the layer guide as a structural starting point, then customize the palette, terrain and details for your world.</div>`;renderLayer();draw3D();renderList()}
function renderLayer(){let l=current.layers[layer];$('#layerLabel').textContent=`Layer ${layer+1} of ${current.layers.length} — ${l.name}`;$('#layerInfo').innerHTML=`<strong>${l.name}</strong><p>${l.note}</p><span>${l.blocks.length} blocks on this layer</span>`;drawTop($('#layerCanvas'),l.blocks,current.size)}
function drawTop(c,blocks,size){let ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#07100a';ctx.fillRect(0,0,w,h);let cell=Math.min((w-80)/size[0],(h-80)/size[1]),ox=(w-cell*size[0])/2,oy=(h-cell*size[1])/2;ctx.strokeStyle='rgba(255,255,255,.08)';for(let x=0;x<=size[0];x++){ctx.beginPath();ctx.moveTo(ox+x*cell,oy);ctx.lineTo(ox+x*cell,oy+size[1]*cell);ctx.stroke()}for(let z=0;z<=size[1];z++){ctx.beginPath();ctx.moveTo(ox,oy+z*cell);ctx.lineTo(ox+size[0]*cell,oy+z*cell);ctx.stroke()}blocks.forEach(v=>{ctx.fillStyle=colors[v.t]||'#78d64b';ctx.fillRect(ox+v.x*cell+1,oy+v.z*cell+1,cell-2,cell-2)});ctx.fillStyle='#a8b5ac';ctx.font='14px sans-serif';ctx.fillText('TOP VIEW',18,26)}
function allBlocks(){return current.layers.flatMap(l=>l.blocks)}
function draw3D(){let c=$('#previewCanvas'),ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#050b07';ctx.fillRect(0,0,W,H);let blocks=allBlocks(),cx=(current.size[0]-1)/2,cy=(current.size[2]-1)/2,cz=(current.size[1]-1)/2;let pts=blocks.map(v=>{let x=v.x-cx,y=v.y-cy,z=v.z-cz;let x1=x*Math.cos(rotY)-z*Math.sin(rotY),z1=x*Math.sin(rotY)+z*Math.cos(rotY);let y1=y*Math.cos(rotX)-z1*Math.sin(rotX),z2=y*Math.sin(rotX)+z1*Math.cos(rotX);return{...v,sx:W/2+x1*26*zoom,sy:H/2-y1*26*zoom,depth:z2}}).sort((a,b)=>a.depth-b.depth);let s=Math.max(4,18*zoom);pts.forEach(p=>{ctx.fillStyle=colors[p.t]||'#78d64b';ctx.globalAlpha=.92;ctx.fillRect(p.sx-s/2,p.sy-s/2,s,s);ctx.strokeStyle='rgba(0,0,0,.35)';ctx.strokeRect(p.sx-s/2,p.sy-s/2,s,s)});ctx.globalAlpha=1;ctx.fillStyle='#91a598';ctx.font='14px sans-serif';ctx.fillText('INTERACTIVE VOXEL PREVIEW',18,26)}
function bind(){let gs=$('#searchGrabCraft'),gq=$('#externalBuildSearch');if(gs&&gq){let go=()=>{let q=gq.value.trim();window.open('https://www.grabcraft.com/search/'+encodeURIComponent(q||'minecraft'),'_blank','noopener')};gs.onclick=go;gq.addEventListener('keydown',e=>{if(e.key==='Enter')go()})}['buildSearch','buildCategory','buildDifficulty'].forEach(id=>$('#'+id).addEventListener(id==='buildSearch'?'input':'change',renderList));$('#buildList').addEventListener('click',e=>{let b=e.target.closest('[data-build]');if(b)selectBuild(b.dataset.build)});$('#prevLayer').onclick=()=>{layer=Math.max(0,layer-1);$('#layerRange').value=layer;renderLayer()};$('#nextLayer').onclick=()=>{layer=Math.min(current.layers.length-1,layer+1);$('#layerRange').value=layer;renderLayer()};$('#layerRange').oninput=e=>{layer=+e.target.value;renderLayer()};$$('[data-academy-tab]').forEach(b=>b.onclick=()=>{$$('[data-academy-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.academy-tab-panel').forEach(x=>x.classList.remove('active'));$('#academy'+b.dataset.academyTab[0].toUpperCase()+b.dataset.academyTab.slice(1)).classList.add('active');if(b.dataset.academyTab==='preview')draw3D()});let c=$('#previewCanvas');c.onpointerdown=e=>{drag=true;last=[e.clientX,e.clientY];c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drag)return;rotY+=(e.clientX-last[0])*.01;rotX+=(e.clientY-last[1])*.01;last=[e.clientX,e.clientY];draw3D()};c.onpointerup=()=>drag=false;c.onwheel=e=>{e.preventDefault();zoom=Math.max(.45,Math.min(2.2,zoom-e.deltaY*.001));draw3D()};$('#resetView').onclick=()=>{rotX=-.55;rotY=.72;zoom=1;draw3D()};$('#sourceEdition').onchange=syncTargets;$('#targetEdition').onchange=()=>{};$('#loadExample').onclick=converterExample;$('#convertBlueprint').onclick=convertBlueprint;$('#blueprintFile').onchange=importBlueprint;$('#downloadBlueprint').onclick=downloadBlueprint}
const map={"minecraft:stone_bricks":"minecraft:stonebrick","minecraft:mossy_stone_bricks":"minecraft:stonebrick","minecraft:oak_planks":"minecraft:planks","minecraft:spruce_planks":"minecraft:planks","minecraft:birch_planks":"minecraft:planks","minecraft:jungle_planks":"minecraft:planks","minecraft:acacia_planks":"minecraft:planks","minecraft:dark_oak_planks":"minecraft:planks","minecraft:grass_block":"minecraft:grass","minecraft:cobblestone":"minecraft:cobblestone","minecraft:iron_bars":"minecraft:iron_bars","minecraft:glass":"minecraft:glass","minecraft:air":"minecraft:air","minecraft:stone":"minecraft:stone","minecraft:dirt":"minecraft:dirt","minecraft:sand":"minecraft:sand","minecraft:gravel":"minecraft:gravel","minecraft:bricks":"minecraft:brick_block","minecraft:oak_log":"minecraft:log","minecraft:spruce_log":"minecraft:log","minecraft:oak_stairs":"minecraft:oak_stairs","minecraft:stone_brick_stairs":"minecraft:stone_brick_stairs","minecraft:torch":"minecraft:torch","minecraft:water":"minecraft:water"};function reverseMap(){let r={};Object.entries(map).forEach(([a,b])=>{if(!r[b])r[b]=a});return r}function syncTargets(){let s=$('#sourceEdition').value;$('#targetEdition').value=s==='java'?'bedrock':'java'}function converterExample(){$('#blueprintInput').value=JSON.stringify({name:'Small Gate',edition:'java',size:[5,3,4],blocks:[{x:0,y:0,z:0,id:'minecraft:stone_bricks'},{x:1,y:0,z:0,id:'minecraft:oak_planks'},{x:2,y:1,z:0,id:'minecraft:iron_bars'}]},null,2)}function convertBlueprint(){try{let d=JSON.parse($('#blueprintInput').value),src=$('#sourceEdition').value,tgt=$('#targetEdition').value,m=src==='java'?map:reverseMap(),unknown=[];d.blocks=(d.blocks||[]).map(v=>{let id=m[v.id];if(!id){unknown.push(v.id);id=v.id}return{...v,id}});d.edition=tgt;d.convertedBy='AetherCraft Blueprint Lab';$('#blueprintOutput').value=JSON.stringify(d,null,2);$('#converterReport').innerHTML=unknown.length?`<strong>Converted with review needed.</strong> ${new Set(unknown).size} identifier(s) had no safe built-in mapping and were preserved unchanged: <code>${[...new Set(unknown)].slice(0,8).join(', ')}</code>`:'<strong>Conversion complete.</strong> Every identifier in this blueprint had a known mapping.'}catch(e){toast('Blueprint JSON is invalid.','default',4500)}}function importBlueprint(e){let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{$('#blueprintInput').value=r.result};r.readAsText(f)}function downloadBlueprint(){let t=$('#blueprintOutput').value;if(!t)return toast('Convert a blueprint first.');let blob=new Blob([t],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`aethercraft-${$('#targetEdition').value}-blueprint.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
if(!dedicatedLoaderGate()){loadConfig();nav();renderAuthActions?.();init()}
