function b(x,y,z,t='stone'){return{x,y,z,t}}
function boxBuild(w,d,h,style='stone',roof=true){let L=[];for(let y=0;y<h;y++){let a=[];for(let x=0;x<w;x++)for(let z=0;z<d;z++){let edge=x===0||x===w-1||z===0||z===d-1;if(y===0)a.push(b(x,y,z,style));else if(y<h-2&&edge){let corner=(x===0||x===w-1)&&(z===0||z===d-1);a.push(b(x,y,z,corner?'wood':style))}else if(roof&&y>=h-2){let inset=y-(h-2);if((z===inset||z===d-1-inset)&&x>=0&&x<w)a.push(b(x,y,z,'roof'))}}L.push({name:y===0?'Foundation':y<h-2?'Walls & frame':'Roof & cap',note:y===0?'Mark the footprint and entrances before building upward.':y<h-2?'Raise the shell evenly and leave openings for doors and windows.':'Finish the silhouette, then add stairs, slabs and trim.',blocks:a})}return L}
function towerBuild(w,d,h){let L=[];for(let y=0;y<h;y++){let a=[];for(let x=0;x<w;x++)for(let z=0;z<d;z++){let edge=x===0||x===w-1||z===0||z===d-1;if(y===0||((y<h-2)&&edge)||((y===h-2)&&(x===0||x===w-1||z===0||z===d-1))||((y===h-1)&&edge&&(x%2===0||z%2===0)))a.push(b(x,y,z,y>h-3?'slab':'stone'))}L.push({name:y===0?'Foundation':y<h-2?'Tower shaft':'Battlements',note:'Keep the footprint square and check symmetry from every side.',blocks:a})}return L}
function flatBuild(w,d,h=3,style='wood'){let L=[];for(let y=0;y<h;y++){let a=[];for(let x=0;x<w;x++)for(let z=0;z<d;z++){if(y===0||y===h-1||x===0||x===w-1||z===0||z===d-1){if((x+z+y)%3!==1||y===0)a.push(b(x,y,z,style))}}L.push({name:y===0?'Footprint':y===h-1?'Finish & detail':'Structure',note:'Use this layer as a guide, then vary blocks and add decorative depth.',blocks:a})}return L}
function bridgeBuild(w,d,h){let L=[];for(let y=0;y<h;y++){let a=[];for(let x=0;x<w;x++)for(let z=0;z<d;z++){let center=(w-1)/2,arch=Math.abs(x-center),deck=y===h-2&&z>0&&z<d-1,rail=y===h-1&&(z===1||z===d-2),support=y<h-2&&(x<3||x>w-4)&&z>0&&z<d-1,curve=y===Math.max(0,h-3-Math.floor(arch/3))&&(z===1||z===d-2);if(deck||rail||support||curve)a.push(b(x,y,z,'stone'))}L.push({name:y<h-2?'Arch & supports':'Deck & rails',note:'Mirror placements from the center and adapt supports to your terrain.',blocks:a})}return L}
const CATALOG=[
['castle','Grand Medieval Castle','Castle','Advanced',[25,21,14],'A full keep with four corner towers, courtyard, battlements and layered defenses.','castle medieval keep battlement courtyard fortress'],
['gatehouse','Castle Gatehouse & Portcullis','Castle','Advanced',[15,11,10],'Twin defensive towers surrounding a central gate and portcullis.','castle gate portcullis defense medieval'],
['castle-wall','Castle Wall Segment','Castle','Intermediate',[17,5,8],'Repeatable defensive wall with walkway, crenellations and arrow slits.','wall castle battlement defense'],
['round-tower','Castle Watchtower','Tower','Intermediate',[11,11,14],'Tall defensive tower for walls, villages and hilltop forts.','tower castle watch medieval'],
['wizard-tower','Fantasy Wizard Tower','Fantasy','Advanced',[13,13,18],'A tall fantasy tower with a dramatic roof and magical detailing.','wizard magic fantasy tower'],
['starter-house','Survival Starter House','House','Beginner',[11,9,7],'Compact starter home with framed walls, roof and useful interior space.','house starter survival cottage'],
['medieval-house','Medieval Timber House','House','Intermediate',[13,11,10],'Timber-frame home with stone base, upper overhang and steep roof.','house medieval timber tudor'],
['modern-house','Modern Survival House','House','Intermediate',[15,11,7],'Clean modern home with glass walls, terraces and simple geometry.','modern house quartz glass'],
['cottage','Cozy Forest Cottage','House','Beginner',[11,9,7],'Small rustic cottage suited to forests and village edges.','cottage forest rustic cozy'],
['farmhouse','Large Farmhouse','House','Intermediate',[17,13,9],'Country farmhouse with porch, chimney and practical survival rooms.','farmhouse country porch house'],
['mansion','Woodland Mansion Inspired Home','House','Advanced',[23,19,12],'Large dark-oak manor with multiple wings and layered rooflines.','mansion manor dark oak house'],
['treehouse','Giant Treehouse','Fantasy','Advanced',[17,17,16],'Elevated wooden home wrapped around a custom tree trunk.','tree treehouse fantasy forest'],
['hobbit','Hillside Burrow','Fantasy','Intermediate',[13,9,6],'Earth-sheltered fantasy home with rounded facade and garden roof.','hobbit burrow hillside fantasy'],
['bridge-stone','Medieval Stone Bridge','Infrastructure','Intermediate',[17,7,6],'Arched stone bridge with rails, supports and lantern posts.','bridge stone medieval road'],
['bridge-wood','Rustic Wooden Bridge','Infrastructure','Beginner',[13,5,4],'Simple curved wooden footbridge for rivers and gardens.','bridge wood rustic river'],
['road','Medieval Road & Path','Infrastructure','Beginner',[15,7,2],'Layered path palette using stone, gravel, dirt and roadside details.','road path medieval gravel decoration'],
['harbor','Harbor Dock','Infrastructure','Intermediate',[17,11,5],'Working-looking dock with piers, cranes, barrels and mooring posts.','dock harbor port ship ocean'],
['windmill','Working-Style Windmill','Infrastructure','Intermediate',[11,11,14],'Classic windmill shell with large blades and milling interior.','windmill farm medieval'],
['lighthouse','Coastal Lighthouse','Tower','Intermediate',[11,11,17],'Tall lighthouse with lantern room and coastal foundation.','lighthouse tower coast ocean'],
['barn','Large Survival Barn','Farm','Intermediate',[17,13,10],'Barn for animals, hay storage and farming supplies.','barn farm animals storage'],
['cropfarm','Decorative Crop Farm','Farm','Beginner',[15,13,3],'Organized crop plots with water, paths, scarecrow and borders.','farm crops wheat carrot potato decoration'],
['greenhouse','Glass Greenhouse','Farm','Intermediate',[13,9,7],'Glass growing house for crops, bees and decorative plants.','greenhouse farm glass plants'],
['stable','Horse Stable','Farm','Beginner',[13,9,6],'Stable with individual stalls, hay loft and fenced paddock.','stable horse farm barn'],
['fountain','Village Fountain','Decoration','Beginner',[9,9,5],'Stone centerpiece with water basin, trim and lantern accents.','fountain decoration village water'],
['garden','Fantasy Garden','Decoration','Beginner',[13,11,4],'Layered garden with paths, flower beds, pond and seating.','garden flowers landscaping decoration'],
['market','Market Stall Set','Decoration','Beginner',[9,7,5],'Colorful merchant stalls with awnings, crates and counters.','market stall decoration village shop'],
['streetlamp','Medieval Streetlamp','Decoration','Beginner',[5,5,6],'Compact lamp-post tutorial for roads, towns and castle courtyards.','lamp lantern decoration street'],
['statue','Knight Statue','Decoration','Intermediate',[9,7,13],'Block-built armored knight monument for plazas and castles.','statue knight monument decoration'],
['throne','Royal Throne Room','Interior','Intermediate',[15,11,7],'Interior layout with throne platform, columns, banners and lighting.','interior throne castle decoration'],
['kitchen','Medieval Kitchen','Interior','Beginner',[11,9,5],'Kitchen detailing with hearth, counters, shelves and food storage.','interior kitchen medieval decoration'],
['bedroom','Cozy Bedroom','Interior','Beginner',[9,7,5],'Detailed bedroom with bed frame, storage, desk and lighting.','interior bedroom furniture decoration'],
['library','Enchanting Library','Interior','Intermediate',[13,9,7],'Tall library with enchanting area, shelves and reading alcoves.','library enchanting interior books'],
['storage','Survival Storage Room','Interior','Beginner',[13,9,5],'Organized storage hall with labeled sections and crafting stations.','storage interior survival chest'],
['netherhub','Nether Hub','Nether','Advanced',[21,21,9],'Large symmetrical Nether transport hub with protected corridors.','nether hub portal travel'],
['netherportal','Custom Nether Portal','Nether','Beginner',[9,7,8],'Decorative portal frame with ruined-stone and lava accents.','nether portal decoration'],
['endtower','End Observatory','Fantasy','Advanced',[15,15,14],'End-themed tower using dark blocks, purple glass and floating details.','end fantasy tower purpur'],
['mine','Mine Entrance','Survival','Beginner',[11,7,6],'Detailed mine entrance with supports, rails and storage.','mine entrance survival cave'],
['warehouse','Bulk Storage Warehouse','Survival','Intermediate',[17,13,8],'Large survival warehouse designed around organized storage aisles.','storage warehouse survival'],
['wallmap','Map Room','Interior','Intermediate',[13,11,6],'Exploration room with map wall, planning table and trophy displays.','map room interior exploration'],
['portalroom','Portal Room','Interior','Intermediate',[13,11,7],'Dedicated Nether portal chamber with dramatic framing and lighting.','portal room interior nether'],
['waterfall','Custom Waterfall','Landscaping','Beginner',[13,9,8],'Natural-looking waterfall with rock shaping, pools and vegetation.','waterfall terrain landscaping water'],
['mountain','Custom Mountain','Landscaping','Advanced',[21,17,14],'Layered terrain method for convincing cliffs, slopes and peaks.','mountain terrain landscaping cliff'],
['customtree','Custom Oak Tree','Landscaping','Intermediate',[13,13,14],'Organic trunk and canopy technique for custom forests.','tree landscaping custom nature'],
['pond','Natural Pond','Landscaping','Beginner',[13,11,4],'Small landscaped pond with depth variation and shoreline plants.','pond water landscaping nature'],
['ruins','Ancient Ruins','Landscaping','Intermediate',[15,13,7],'Broken walls, collapsed arches and overgrowth for environmental storytelling.','ruins ancient landscaping decoration'],
['redstone-door','Hidden Piston Door Shell','Redstone','Intermediate',[9,5,6],'Build-friendly facade and cavity plan for a compact hidden entrance.','redstone piston door secret'],
['item-sorter','Item Sorter Housing','Redstone','Intermediate',[13,9,6],'Organized exterior and service corridor for a modular item sorter.','redstone sorter storage automation'],
['super-smelter','Super Smelter Building','Redstone','Advanced',[17,11,7],'Industrial shell designed around furnace arrays and item transport.','redstone smelter automation furnace'],
['mobfarm','Mob Farm Exterior','Farm','Advanced',[17,17,18],'Build shell and tower layout for disguising a hostile-mob farm.','mob farm survival automation'],
['ironfarm','Iron Farm Village Shell','Farm','Advanced',[17,15,10],'Decorative village-inspired housing around an iron farm footprint.','iron farm automation village'],
['bee','Bee Sanctuary','Farm','Beginner',[13,11,6],'Flower-rich apiary with hives, greenhouse details and paths.','bee honey farm flowers'],
['ship','Medieval Sailing Ship','Vehicle','Advanced',[25,9,17],'Layered hull, decks, masts and sails for a large sailing vessel.','ship boat medieval ocean'],
['airship','Fantasy Airship','Vehicle','Advanced',[21,11,15],'Steampunk-inspired flying vessel with balloon frame and gondola.','airship fantasy steampunk vehicle'],
['wagon','Medieval Wagon','Vehicle','Beginner',[9,5,5],'Small wagon for roads, farms and market scenes.','wagon cart medieval decoration'],
['dragon','Block Dragon Statue','Pixel Art','Advanced',[19,13,15],'Large dragon sculpture using silhouette-first organic shaping.','dragon statue pixel art fantasy'],
['logo','Pixel Art Logo Board','Pixel Art','Beginner',[17,3,12],'Grid-based method for converting simple logos into block art.','pixel art logo mural'],
['arena','PvP Arena','Community','Advanced',[25,21,10],'Symmetrical combat arena with stands, entrances and spectator zones.','arena pvp community stadium'],
['spawn','Server Spawn Plaza','Community','Advanced',[27,27,12],'Central multiplayer spawn with portals, paths, information boards and landmarks.','spawn server community hub'],
['shop','Player Shop','Community','Beginner',[11,9,7],'Compact storefront for survival servers and marketplace districts.','shop store market community'],
['portalhub','Portal Hub','Community','Advanced',[23,23,10],'Large multi-portal hub organized around a central landmark.','portal hub server travel community'],
['cathedral','Grand Medieval Cathedral','Religious','Advanced',[25,17,20],'Large stone cathedral with nave, towers, stained-glass bays and vaulted silhouette.','cathedral church medieval gothic stained glass'],
['chapel','Village Stone Chapel','Religious','Intermediate',[13,9,11],'Compact village chapel with bell tower, altar and graveyard-friendly footprint.','chapel church village medieval'],
['monastery','Mountain Monastery','Religious','Advanced',[23,17,12],'Cliffside monastery complex with cloister courtyard and terraced gardens.','monastery mountain medieval temple'],
['japanese-temple','Japanese Temple','Cultural','Advanced',[19,15,13],'Layered temple with sweeping rooflines, lantern path and raised foundation.','japanese temple pagoda asian shrine'],
['pagoda','Five-Story Pagoda','Cultural','Advanced',[15,15,21],'Tall multi-tier pagoda focused on repeating roof proportions and symmetry.','pagoda japanese tower asian'],
['viking-hall','Viking Longhouse','Cultural','Intermediate',[21,11,9],'Long timber hall with steep roof, hearth and carved entrance framing.','viking longhouse nordic hall medieval'],
['desert-palace','Desert Palace','Cultural','Advanced',[25,21,12],'Sandstone palace with courtyards, domes, towers and shaded arcades.','desert palace sandstone arabian oasis'],
['desert-house','Desert Village House','House','Beginner',[11,9,6],'Compact sandstone home with shaded roof terrace and market details.','desert house sandstone village'],
['snow-cabin','Snowy Taiga Cabin','House','Beginner',[11,9,7],'Warm spruce cabin designed for snowy forests and survival worlds.','snow cabin taiga spruce survival'],
['swamp-house','Swamp Stilt House','House','Intermediate',[13,11,8],'Raised house on stilts with boardwalk and mangrove-inspired detailing.','swamp stilt mangrove house'],
['mushroom-house','Fantasy Mushroom House','Fantasy','Intermediate',[13,13,11],'Whimsical mushroom-shaped cottage with curved cap and organic interior.','mushroom fantasy cottage fairy'],
['elven-house','Elven Forest Home','Fantasy','Advanced',[17,15,12],'Elegant forest home blending custom trees, arches and natural materials.','elf elven fantasy forest house'],
['dwarven-gate','Dwarven Mountain Gate','Fantasy','Advanced',[23,9,16],'Monumental carved mountain entrance with statues and deep stone framing.','dwarf dwarven mountain gate fantasy'],
['dragon-statue','Dragon Statue','Statue','Advanced',[21,11,15],'Large dragon sculpture with wings, tail and raised display base.','dragon statue fantasy sculpture'],
['horse-statue','Horse Statue','Statue','Intermediate',[13,7,12],'Decorative horse monument for castles, towns and racetracks.','horse statue sculpture decoration'],
['sword-statue','Giant Sword Monument','Statue','Intermediate',[9,7,18],'Oversized sword monument with pedestal and optional glowing accents.','sword statue monument fantasy'],
['townhall','Medieval Town Hall','Community','Advanced',[21,17,12],'Large civic building with council chamber, clock facade and market-facing entrance.','town hall medieval city community'],
['blacksmith','Village Blacksmith','Village','Intermediate',[13,11,7],'Forge, chimney, workshop and storage yard for a believable smithy.','blacksmith forge village medieval'],
['bakery','Village Bakery','Village','Beginner',[11,9,7],'Cozy bakery with oven, storefront, kitchen and upstairs living space.','bakery shop village food medieval'],
['tavern','Medieval Tavern & Inn','Village','Intermediate',[15,13,10],'Busy tavern with bar, kitchen, fireplace and guest rooms upstairs.','tavern inn medieval village pub'],
['apothecary','Fantasy Apothecary','Village','Intermediate',[11,9,9],'Narrow fantasy shop with herb storage, potion workspace and crooked roofline.','apothecary potion shop fantasy village'],
['fishmarket','Harbor Fish Market','Village','Intermediate',[15,11,6],'Covered fish market with counters, crates, ice displays and dock access.','fish market harbor village shop'],
['city-gate','Grand City Gate','Infrastructure','Advanced',[21,9,14],'Monumental city entrance with guard towers, archway and raised wall walk.','city gate wall medieval entrance'],
['aqueduct','Roman Aqueduct','Infrastructure','Intermediate',[25,5,11],'Repeatable stone aqueduct section using tall arches and water channel.','aqueduct roman bridge water infrastructure'],
['canal','Town Canal','Infrastructure','Intermediate',[21,9,5],'Urban canal with retaining walls, stairs, bridges and waterside paths.','canal town water bridge infrastructure'],
['train-station','Railway Station','Infrastructure','Advanced',[25,15,10],'Large station shell with platforms, canopy and ticket hall.','train railway station rail minecart'],
['minecart-station','Survival Minecart Station','Infrastructure','Intermediate',[15,11,7],'Compact rail hub with arrivals, departures and storage siding.','minecart railway station survival'],
['suspension-bridge','Suspension Bridge','Infrastructure','Advanced',[31,7,12],'Long-span bridge with towers, suspended deck and cable-like chains.','bridge suspension river infrastructure'],
['watermill','River Watermill','Infrastructure','Intermediate',[15,11,10],'Riverside mill with wheel housing, storage floor and rustic roof.','watermill river medieval mill'],
['well','Village Well','Decoration','Beginner',[7,7,6],'Small functional-looking well with canopy, crank and stone basin.','well village decoration water'],
['campfire-site','Forest Campsite','Decoration','Beginner',[11,9,4],'Campsite with fire pit, tents, logs, supplies and trail details.','camp campsite forest decoration survival'],
['graveyard','Old Graveyard','Decoration','Intermediate',[15,13,5],'Atmospheric cemetery with varied graves, paths, trees and ruined wall.','graveyard cemetery spooky decoration'],
['clocktower','City Clock Tower','Tower','Advanced',[13,13,22],'Tall civic clock tower with visible clock faces and observation level.','clock tower city medieval'],
['bell-tower','Village Bell Tower','Tower','Intermediate',[9,9,15],'Open-sided bell tower suited to village centers and churches.','bell tower village decoration'],
['siege-tower','Medieval Siege Tower','Vehicle','Intermediate',[9,7,13],'Wooden rolling siege tower with ramps, platforms and defensive siding.','siege tower medieval vehicle war'],
['catapult','Medieval Catapult','Vehicle','Intermediate',[11,7,7],'Decorative siege catapult with throwing arm, wheels and rope details.','catapult siege medieval vehicle'],
['wagon','Merchant Wagon','Vehicle','Beginner',[9,5,5],'Covered merchant wagon with wheels, cargo and hitching details.','wagon cart merchant vehicle medieval'],
['carriage','Royal Carriage','Vehicle','Intermediate',[11,5,6],'Decorative royal carriage with enclosed cabin and ornate trim.','carriage royal wagon vehicle'],
['submarine','Small Submarine','Vehicle','Advanced',[19,9,8],'Underwater vehicle shell with observation windows and interior compartments.','submarine ocean vehicle underwater'],
['spaceship','Sci-Fi Spaceship','Sci-Fi','Advanced',[25,17,9],'Futuristic spacecraft with cockpit, engines, wings and cargo bay.','spaceship scifi futuristic vehicle'],
['space-station','Orbital Space Station','Sci-Fi','Advanced',[29,29,13],'Large modular station with central hub, solar wings and docking arms.','space station scifi futuristic'],
['laboratory','Redstone Laboratory','Sci-Fi','Intermediate',[17,13,8],'Technical laboratory interior with testing bays and redstone displays.','laboratory redstone scifi interior'],
['bunker','Underground Bunker','Survival','Advanced',[19,15,7],'Protected underground base with airlock-style entry, storage and farms.','bunker underground survival base'],
['mountain-base','Hidden Mountain Base','Survival','Advanced',[21,13,9],'Concealed base facade with hangar-like entrance and interior levels.','mountain base hidden survival'],
['ocean-base','Underwater Ocean Base','Survival','Advanced',[21,21,10],'Glass-domed underwater base with connecting tunnels and observation rooms.','ocean underwater base survival glass'],
['sky-base','Floating Sky Base','Fantasy','Advanced',[23,23,12],'Floating island base with waterfalls, towers and suspended bridges.','sky floating island base fantasy'],
['bee-farm','Bee Farm & Apiary','Farm','Beginner',[13,9,6],'Decorative apiary with flowers, bee nests and honey processing area.','bee apiary honey farm flowers'],
['animal-barn','Animal Barn Complex','Farm','Intermediate',[21,15,9],'Multi-pen barn for cows, sheep, pigs and chickens with feed storage.','animals barn farm pens'],
['orchard','Fruit Orchard Layout','Farm','Beginner',[17,15,4],'Organized orchard with custom trees, paths, carts and storage shed.','orchard trees farm garden'],
['fishing-hut','Fishing Hut','Survival','Beginner',[11,9,6],'Waterside survival hut with dock, fish storage and boat mooring.','fishing hut dock survival'],
['mob-farm-shell','Mob Farm Tower Shell','Farm','Intermediate',[13,13,20],'Exterior shell and service access for disguising a technical mob farm.','mob farm tower technical'],
['super-smelter','Super Smelter Hall','Redstone','Advanced',[17,11,7],'Organized hall designed around furnace arrays, inputs and outputs.','redstone smelter furnace automation'],
['vault-door','Redstone Vault Door Facade','Redstone','Advanced',[13,7,9],'Heavy vault facade with space reserved for piston/redstone mechanisms.','vault door redstone piston secret'],
['elevator','Bubble Elevator Tower','Redstone','Beginner',[7,7,14],'Decorative vertical shaft for soul-sand and magma bubble elevators.','elevator bubble water redstone survival'],
['rollercoaster','Minecart Rollercoaster','Redstone','Advanced',[27,21,12],'Theme-park track layout with station, climbs, drops and scenery.','rollercoaster minecart redstone amusement'],
['maze','Garden Hedge Maze','Landscaping','Intermediate',[21,21,4],'Symmetrical hedge maze with central landmark and hidden shortcuts.','maze hedge garden landscaping'],
['volcano','Custom Volcano','Landscaping','Advanced',[25,25,17],'Layered volcanic mountain with crater, lava channels and blackstone slopes.','volcano mountain lava landscaping'],
['beach','Tropical Beach','Landscaping','Beginner',[21,15,5],'Shaped shoreline with palms, rocks, umbrellas and shallow-water details.','beach tropical ocean landscaping'],
['cave','Custom Lush Cave','Landscaping','Advanced',[21,17,11],'Hand-shaped cave chamber with pools, moss, vines and layered rock ceiling.','cave lush landscaping underground'],
['server-lobby','Grand Server Lobby','Community','Advanced',[31,31,15],'Large multiplayer lobby with portals, information boards and central landmark.','server lobby spawn multiplayer community'],
['parkour-course','Parkour Course','Community','Intermediate',[25,15,9],'Progressive parkour route with checkpoints, themes and spectator paths.','parkour server minigame community'],
['spleef-arena','Spleef Arena','Community','Intermediate',[21,21,8],'Round multiplayer arena with spectator ring and replaceable floor.','spleef arena minigame server'],
['market-square','Town Market Square','Community','Intermediate',[23,19,7],'Central plaza with stalls, fountain, seating and road connections.','market square town community village'],
['adventure-guild','Adventurers Guild Hall','Fantasy','Advanced',[19,15,11],'Guild headquarters with quest board, trophy hall and meeting room.','guild fantasy tavern adventure hall'],

['fortress-keep','Fortified Stone Keep','Castle','Advanced',[25,21,18],'A defensive stone keep with corner towers, battlements, great hall and inner courtyard.','castle fortress keep stone medieval'],
['castle-courtyard','Castle Inner Courtyard','Castle','Intermediate',[23,19,7],'A lived-in castle courtyard with well, stables, training yard, arcades and greenery.','castle courtyard medieval decoration'],
['castle-kitchen','Castle Great Kitchen','Interior','Intermediate',[15,11,7],'Large medieval kitchen with hearths, preparation tables, pantry shelving and hanging storage.','castle kitchen medieval interior'],
['castle-dungeon','Castle Dungeon','Interior','Intermediate',[17,13,6],'Underground dungeon with cells, guard station, chains, storage and stone corridors.','castle dungeon medieval underground'],
['castle-barracks','Castle Barracks','Interior','Intermediate',[17,11,7],'Practical barracks with bunks, weapon racks, lockers and officers corner.','castle barracks medieval interior'],
['castle-portcullis','Double Portcullis Gate','Castle','Advanced',[17,11,14],'Heavy gate passage with twin portcullises, murder-hole gallery and defensive towers.','castle portcullis gate gatehouse medieval'],
['spruce-lodge','Spruce Mountain Lodge','House','Intermediate',[17,13,9],'Warm spruce lodge with stone chimney, balcony, steep roof and mountain-ready foundation.','spruce lodge mountain house survival'],
['oak-village-home','Oak Village Home','House','Beginner',[13,11,8],'Classic oak-and-cobblestone village home with porch, loft and compact storage.','oak village house survival'],
['dark-oak-manor','Dark Oak Manor','House','Advanced',[23,17,12],'Large dark-oak manor with stone foundation, wings, balconies and layered roofs.','dark oak manor mansion house'],
['cherry-house','Cherry Grove House','House','Intermediate',[15,13,9],'Pink cherry-wood home with white accents, garden terrace and curved roof details.','cherry grove house pink'],
['mangrove-house','Mangrove Swamp House','House','Intermediate',[15,13,8],'Raised mangrove home with roots, boardwalks and swamp-friendly storage.','mangrove swamp house survival'],
['desert-villa','Sandstone Desert Villa','House','Intermediate',[17,15,8],'Cool sandstone villa with shaded courtyard, fountain and rooftop terrace.','sandstone desert villa house'],
['blacksmith-forge','Detailed Blacksmith Forge','Community','Intermediate',[15,11,8],'Working-looking forge with chimney, smithing floor, storage yard and storefront.','blacksmith forge village medieval'],
['bakery','Village Bakery','Community','Beginner',[13,9,7],'Cozy bakery with ovens, counter, flour storage and street-facing display.','bakery village shop decoration'],
['apothecary','Fantasy Apothecary','Community','Intermediate',[13,11,9],'Potion shop with crooked timber frame, herb racks and colorful bottle displays.','apothecary potion fantasy shop'],
['flower-shop','Flower Shop','Community','Beginner',[11,9,7],'Small colorful flower shop with awning, planters and compact upstairs room.','flower shop village decoration'],
['townhouse-row','Medieval Townhouse Row','Community','Advanced',[27,11,11],'Connected row of varied timber townhouses for dense medieval streets.','townhouse medieval city street'],
['city-alley','Detailed Medieval Alley','Decoration','Intermediate',[17,7,7],'Narrow alley with overhangs, drains, crates, signs, lanterns and clutter.','alley medieval decoration city'],
['camp-site','Survival Campsite','Decoration','Beginner',[13,11,4],'Outdoor campsite with tents, campfire, log seating, supply crates and wagon.','camp campsite survival decoration'],
['picnic-area','Forest Picnic Area','Decoration','Beginner',[13,11,4],'Tables, canopy, firepit, trail signs and landscaping for a forest rest stop.','picnic forest decoration landscaping'],
['dock-house','Fisherman Dock House','House','Intermediate',[15,13,8],'Weathered spruce dock house with pier, nets, barrels and boat shelter.','spruce dock fishing house'],
['water-wheel','River Water Wheel','Infrastructure','Intermediate',[13,9,10],'Large decorative water wheel with timber supports and mill connection.','water wheel river mill infrastructure'],
['stone-aqueduct','Grand Stone Aqueduct','Infrastructure','Advanced',[29,7,13],'Long repeating stone arches carrying a water channel across terrain.','aqueduct stone roman infrastructure'],
['canal-lock','Canal Lock','Infrastructure','Intermediate',[19,11,6],'Working-style canal lock with gates, towpath, control hut and stone retaining walls.','canal lock water infrastructure'],
['covered-bridge','Covered Spruce Bridge','Infrastructure','Intermediate',[19,7,8],'Roofed timber bridge using spruce beams, stone piers and lantern lighting.','spruce covered bridge river'],
['watch-camp','Frontier Watch Camp','Survival','Beginner',[15,13,6],'Small defensive camp with watch platform, tents, palisade and supply area.','survival camp watch frontier'],
['quarry','Stone Quarry','Survival','Intermediate',[21,17,8],'Excavated quarry scene with crane, carts, scaffolds and stone-processing yard.','quarry mine stone survival'],
['lumber-yard','Lumber Yard','Survival','Intermediate',[19,15,7],'Logging yard with stacked timber, saw shed, crane and work platforms.','lumber spruce oak logs survival'],
['enchanting-tower','Enchanting Tower','Fantasy','Intermediate',[13,13,15],'Compact magical tower with enchanting room, crystal-like accents and dramatic roof.','enchanting tower fantasy magic'],
['witch-hut-deluxe','Expanded Witch Hut','Fantasy','Intermediate',[13,11,9],'Swamp witch home with potion room, crooked roof, dock and overgrown details.','witch hut swamp fantasy'],
['giant-mushroom-home','Giant Mushroom Home','Fantasy','Intermediate',[15,15,12],'Whimsical mushroom-shaped home with curved stem rooms and colorful cap roof.','mushroom fantasy house'],
['ice-palace','Ice Palace','Fantasy','Advanced',[27,23,17],'Frozen palace with ice spires, blue-glass halls and symmetrical ceremonial entrance.','ice palace frozen fantasy castle'],
['nether-fort','Custom Nether Fortress','Nether','Advanced',[27,21,15],'Blackstone fortress with lava channels, bridges, bastions and portal chamber.','nether fortress blackstone lava'],
['end-base','End Island Base','Survival','Advanced',[21,19,10],'Protected End base with chorus garden, storage, gateway shelter and viewing deck.','end base survival purpur'],
['copper-factory','Copper Factory','Redstone','Advanced',[23,17,11],'Industrial copper factory shell with smokestacks, machine bays and redstone service floors.','copper factory industrial redstone'],
['rail-station','Grand Rail Station','Infrastructure','Advanced',[29,17,12],'Large station with multiple platforms, ticket hall, canopy and rail-side details.','rail train station infrastructure'],
['nether-rail','Nether Rail Terminal','Nether','Intermediate',[19,13,9],'Protected Nether rail terminal with arrival platforms, portals and blast-resistant shell.','nether rail station travel'],
['ice-road-hub','Nether Ice Road Hub','Nether','Advanced',[25,25,9],'Central packed/blue-ice travel hub with boat lanes and labeled destination portals.','nether ice road hub travel'],
['storage-silo','Bulk Storage Silo','Survival','Intermediate',[15,15,13],'Tall warehouse-style storage silo with categorized floors and loading area.','storage silo survival warehouse'],
['trophy-hall','Achievement Trophy Hall','Interior','Intermediate',[17,13,8],'Display hall for rare items, armor, mob heads, maps and server achievements.','trophy achievement interior display']
];
function chooseLayers(r){let [w,d,h]=r[4],cat=r[2];if(cat==='Tower')return towerBuild(w,d,h);if(cat==='Infrastructure'&&r[0].includes('bridge'))return bridgeBuild(w,d,h);if(['Decoration','Interior','Landscaping','Pixel Art','Vehicle','Redstone'].includes(cat))return flatBuild(w,d,Math.min(h,7),cat==='Interior'?'plank':cat==='Landscaping'?'stone':'wood');return boxBuild(w,d,h,cat==='House'?'plank':'stone',!['Farm','Community'].includes(cat))}
function materialPalette(r){
 const [w,d,h]=r[4], cat=r[2], text=(r[1]+' '+r[5]+' '+r[6]).toLowerCase();
 const scale=Math.max(1,Math.round((w*d+h*12)/180));
 const qty=(base)=>Math.max(4,Math.round(base*scale/8)*8);
 let wood=text.includes('spruce')?'Spruce':text.includes('dark oak')?'Dark Oak':text.includes('oak')?'Oak':text.includes('cherry')?'Cherry':text.includes('mangrove')?'Mangrove':text.includes('japanese')?'Dark Oak':'Spruce';
 let p=[];
 if(cat==='House'||cat==='Community'||cat==='Farm') p=[[wood+' Planks',qty(128)],[wood+' Logs',qty(64)],['Stripped '+wood+' Logs',qty(40)],[wood+' Stairs',qty(72)],[wood+' Slabs',qty(48)],['Cobblestone',qty(72)],['Stone Bricks',qty(48)],['Glass Panes',qty(24)],['Lanterns',qty(8)],['Trapdoors',qty(16)]];
 else if(cat==='Castle'||cat==='Tower'||cat==='Religious') p=[['Stone Bricks',qty(180)],['Cobblestone',qty(96)],['Cracked Stone Bricks',qty(48)],['Mossy Stone Bricks',qty(32)],['Stone Brick Stairs',qty(80)],['Stone Brick Slabs',qty(56)],['Spruce Planks',qty(48)],['Spruce Logs',qty(32)],['Iron Bars',qty(20)],['Lanterns',qty(12)]];
 else if(cat==='Interior') p=[[wood+' Planks',qty(96)],[wood+' Stairs',qty(48)],[wood+' Slabs',qty(32)],[wood+' Trapdoors',qty(24)],['Barrels',qty(12)],['Bookshelves',qty(16)],['Chains',qty(8)],['Lanterns',qty(8)],['Carpets',qty(20)],['Item Frames',qty(8)]];
 else if(cat==='Decoration'||cat==='Pixel Art') p=[['Stone Bricks',qty(48)],[wood+' Planks',qty(40)],[wood+' Stairs',qty(24)],[wood+' Slabs',qty(24)],[wood+' Trapdoors',qty(12)],['Fences',qty(12)],['Lanterns',qty(6)],['Chains',qty(6)],['Flower Pots',qty(6)],['Leaves',qty(20)]];
 else if(cat==='Landscaping') p=[['Grass Blocks',qty(128)],['Dirt',qty(96)],['Stone',qty(96)],['Cobblestone',qty(48)],['Moss Blocks',qty(40)],['Oak Leaves',qty(64)],['Oak Logs',qty(32)],['Flowers',qty(32)],['Water Buckets',4],['Coarse Dirt',qty(32)]];
 else if(cat==='Redstone') p=[['Stone Bricks',qty(96)],['Redstone Dust',qty(40)],['Redstone Repeaters',qty(12)],['Redstone Comparators',qty(8)],['Sticky Pistons',qty(12)],['Observers',qty(12)],['Hoppers',qty(16)],['Redstone Torches',qty(12)],['Spruce Planks',qty(48)],['Glass',qty(24)]];
 else if(cat==='Nether') p=[['Blackstone',qty(128)],['Polished Blackstone Bricks',qty(128)],['Basalt',qty(64)],['Nether Bricks',qty(80)],['Crimson Planks',qty(48)],['Blackstone Stairs',qty(48)],['Blackstone Slabs',qty(32)],['Chains',qty(12)],['Soul Lanterns',qty(10)],['Magma Blocks',qty(24)]];
 else if(cat==='Infrastructure'||cat==='Vehicle') p=[['Stone Bricks',qty(112)],[wood+' Planks',qty(96)],[wood+' Logs',qty(56)],[wood+' Stairs',qty(48)],[wood+' Slabs',qty(40)],['Cobblestone',qty(56)],['Fences',qty(24)],['Iron Bars',qty(16)],['Lanterns',qty(10)],['Chains',qty(8)]];
 else if(cat==='Fantasy'||cat==='Cultural'||cat==='Sci-Fi') p=[[wood+' Planks',qty(96)],['Stone Bricks',qty(96)],[wood+' Logs',qty(48)],[wood+' Stairs',qty(48)],['Glass',qty(32)],['Deepslate Tiles',qty(48)],['Quartz Blocks',qty(32)],['Lanterns',qty(10)],['Chains',qty(8)],['Decorative Accent Blocks',qty(32)]];
 else p=[['Stone Bricks',qty(112)],['Cobblestone',qty(72)],[wood+' Planks',qty(80)],[wood+' Logs',qty(40)],[wood+' Stairs',qty(40)],[wood+' Slabs',qty(32)],['Glass Panes',qty(20)],['Fences',qty(16)],['Lanterns',qty(8)],['Trapdoors',qty(12)]];
 return p;
}
const BUILDS=CATALOG.map(r=>({id:r[0],title:r[1],category:r[2],difficulty:r[3],size:r[4],desc:r[5],tags:r[6].split(' '),materials:materialPalette(r),tips:tipsFor(r[2]),layers:chooseLayers(r)}));
function tipsFor(cat){const base=['Build the main silhouette before spending time on tiny details.','Use temporary blocks to mark the center line and major corners.','Mix block variants in small amounts to avoid flat-looking walls.','Walk around the build often and check it from player eye level.'];const extra={Castle:'Use towers and wall depth to create a believable defensive structure.',Decoration:'Small asymmetry usually makes decorative builds feel more natural.',Landscaping:'Avoid perfect circles and straight terrain edges; vary height gradually.',Interior:'Leave walking space first, then add furniture around the movement path.',Redstone:'Test the mechanism in a creative copy before enclosing it in decoration.',Farm:'Confirm the farm mechanics for your exact Minecraft edition/version before decorating it.'};return [...base,extra[cat]||'Adapt the palette to the biome and materials available on your world.']}
const colors={stone:'#778079',wood:'#5d3b24',plank:'#a87949',roof:'#4a2d1c',iron:'#b8c1c1',slab:'#89908b'};let current=BUILDS[0],layer=0,rotX=-.55,rotY=.72,zoom=1,drag=false,last=[0,0];
function init(){populateFilters();renderStats();renderList();selectBuild(current.id);bind();}
function populateFilters(){[...new Set(BUILDS.map(x=>x.category))].forEach(c=>$('#buildCategory').insertAdjacentHTML('beforeend',`<option>${c}</option>`))}
function renderStats(){let el=$('#academyStats');if(!el)return;let cats=new Set(BUILDS.map(x=>x.category));el.innerHTML=`<div class="academy-stat"><strong>${BUILDS.length}</strong><span>built-in tutorials</span></div><div class="academy-stat"><strong>${cats.size}</strong><span>build categories</span></div><div class="academy-stat"><strong>${BUILDS.reduce((n,x)=>n+x.layers.length,0)}</strong><span>guided layers</span></div><div class="academy-stat"><strong>Java + Bedrock</strong><span>planning support</span></div>`}function renderList(){let q=$('#buildSearch').value.toLowerCase().trim(),cat=$('#buildCategory').value,d=$('#buildDifficulty').value;let rows=BUILDS.filter(x=>(cat==='all'||x.category===cat)&&(d==='all'||x.difficulty===d)&&(`${x.title} ${x.category} ${x.desc} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(q)));$('#buildList').innerHTML=rows.map(x=>`<button class="academy-build-card ${x.id===current?.id?'active':''}" data-build="${x.id}"><span>${x.category} • ${x.difficulty}</span><strong>${x.title}</strong><small>${x.size.join(' × ')}</small><em>${(x.tags||[]).slice(0,4).join(' • ')}</em></button>`).join('')||`<div class="academy-empty"><strong>No built-in tutorial found.</strong><p>Try a broader term or use the external tutorial searches below.</p></div>`}
function selectBuild(id){current=BUILDS.find(x=>x.id===id)||BUILDS[0];layer=0;$('#buildIntro').hidden=true;$('#buildWorkspace').hidden=false;$('#buildMeta').textContent=`${current.category} • ${current.difficulty}`;$('#buildTitle').textContent=current.title;$('#buildDescription').textContent=current.desc;$('#buildDimensions').innerHTML=`<strong>${current.size.join(' × ')}</strong><span>blocks wide × deep × high</span>`;$('#layerRange').max=current.layers.length-1;$('#layerRange').value=0;$('#materialsGrid').innerHTML=current.materials.map(m=>`<div><strong>${m[1]}</strong><span>${m[0]}</span></div>`).join('');$('#tipsContent').innerHTML=`<ol class="build-tip-list">${current.tips.map(t=>`<li>${t}</li>`).join('')}</ol><div class="academy-tags">${(current.tags||[]).map(t=>`<span class="academy-tag">${t}</span>`).join('')}</div><div class="academy-resources"><a class="academy-resource" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${encodeURIComponent('Minecraft '+current.title+' tutorial')}"><strong>Search video tutorials ↗</strong><span>Find additional visual references for this build.</span></a><a class="academy-resource" target="_blank" rel="noopener" href="https://www.planetminecraft.com/projects/?keywords=${encodeURIComponent(current.title)}"><strong>Search Planet Minecraft ↗</strong><span>Browse related community builds and inspiration.</span></a></div><div class="notice"><strong>Creative tip:</strong> Use the layer guide as a structural starting point, then customize the palette, terrain and details for your world.</div>`;renderLayer();draw3D();renderList()}
function renderLayer(){let l=current.layers[layer];$('#layerLabel').textContent=`Layer ${layer+1} of ${current.layers.length} — ${l.name}`;$('#layerInfo').innerHTML=`<strong>${l.name}</strong><p>${l.note}</p><span>${l.blocks.length} blocks on this layer</span>`;drawTop($('#layerCanvas'),l.blocks,current.size)}
function drawTop(c,blocks,size){let ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#07100a';ctx.fillRect(0,0,w,h);let cell=Math.min((w-80)/size[0],(h-80)/size[1]),ox=(w-cell*size[0])/2,oy=(h-cell*size[1])/2;ctx.strokeStyle='rgba(255,255,255,.08)';for(let x=0;x<=size[0];x++){ctx.beginPath();ctx.moveTo(ox+x*cell,oy);ctx.lineTo(ox+x*cell,oy+size[1]*cell);ctx.stroke()}for(let z=0;z<=size[1];z++){ctx.beginPath();ctx.moveTo(ox,oy+z*cell);ctx.lineTo(ox+size[0]*cell,oy+z*cell);ctx.stroke()}blocks.forEach(v=>{ctx.fillStyle=colors[v.t]||'#78d64b';ctx.fillRect(ox+v.x*cell+1,oy+v.z*cell+1,cell-2,cell-2)});ctx.fillStyle='#a8b5ac';ctx.font='14px sans-serif';ctx.fillText('TOP VIEW',18,26)}
function allBlocks(){return current.layers.flatMap(l=>l.blocks)}
function draw3D(){let c=$('#previewCanvas'),ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#050b07';ctx.fillRect(0,0,W,H);let blocks=allBlocks(),cx=(current.size[0]-1)/2,cy=(current.size[2]-1)/2,cz=(current.size[1]-1)/2;let pts=blocks.map(v=>{let x=v.x-cx,y=v.y-cy,z=v.z-cz;let x1=x*Math.cos(rotY)-z*Math.sin(rotY),z1=x*Math.sin(rotY)+z*Math.cos(rotY);let y1=y*Math.cos(rotX)-z1*Math.sin(rotX),z2=y*Math.sin(rotX)+z1*Math.cos(rotX);return{...v,sx:W/2+x1*26*zoom,sy:H/2-y1*26*zoom,depth:z2}}).sort((a,b)=>a.depth-b.depth);let s=Math.max(4,18*zoom);pts.forEach(p=>{ctx.fillStyle=colors[p.t]||'#78d64b';ctx.globalAlpha=.92;ctx.fillRect(p.sx-s/2,p.sy-s/2,s,s);ctx.strokeStyle='rgba(0,0,0,.35)';ctx.strokeRect(p.sx-s/2,p.sy-s/2,s,s)});ctx.globalAlpha=1;ctx.fillStyle='#91a598';ctx.font='14px sans-serif';ctx.fillText('INTERACTIVE VOXEL PREVIEW',18,26)}
function bind(){let gs=$('#searchGrabCraft'),gq=$('#externalBuildSearch');if(gs&&gq){let go=()=>{let q=gq.value.trim();window.open('https://www.grabcraft.com/search/'+encodeURIComponent(q||'minecraft'),'_blank','noopener')};gs.onclick=go;gq.addEventListener('keydown',e=>{if(e.key==='Enter')go()})}['buildSearch','buildCategory','buildDifficulty'].forEach(id=>$('#'+id).addEventListener(id==='buildSearch'?'input':'change',renderList));$('#buildList').addEventListener('click',e=>{let b=e.target.closest('[data-build]');if(b)selectBuild(b.dataset.build)});$('#prevLayer').onclick=()=>{layer=Math.max(0,layer-1);$('#layerRange').value=layer;renderLayer()};$('#nextLayer').onclick=()=>{layer=Math.min(current.layers.length-1,layer+1);$('#layerRange').value=layer;renderLayer()};$('#layerRange').oninput=e=>{layer=+e.target.value;renderLayer()};$$('[data-academy-tab]').forEach(b=>b.onclick=()=>{$$('[data-academy-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.academy-tab-panel').forEach(x=>x.classList.remove('active'));$('#academy'+b.dataset.academyTab[0].toUpperCase()+b.dataset.academyTab.slice(1)).classList.add('active');if(b.dataset.academyTab==='preview')draw3D()});let c=$('#previewCanvas');c.onpointerdown=e=>{drag=true;last=[e.clientX,e.clientY];c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drag)return;rotY+=(e.clientX-last[0])*.01;rotX+=(e.clientY-last[1])*.01;last=[e.clientX,e.clientY];draw3D()};c.onpointerup=()=>drag=false;c.onwheel=e=>{e.preventDefault();zoom=Math.max(.45,Math.min(2.2,zoom-e.deltaY*.001));draw3D()};$('#resetView').onclick=()=>{rotX=-.55;rotY=.72;zoom=1;draw3D()}}

function startBuildAcademy(){try{init()}catch(err){console.error('Build Academy failed to initialize:',err);const list=document.getElementById('buildList');if(list)list.innerHTML='<div class="notice"><strong>Build library could not initialize.</strong><p>Refresh the page. If this persists, check the browser console for the exact error.</p></div>'}}
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',startBuildAcademy,{once:true}); else startBuildAcademy();
