function profileTopics(){try{return JSON.parse(localStorage.getItem('ac_topics')||'[]')}catch{return []}}
function calculateProfileStats(name){const key=String(name||'').toLowerCase(),topics=profileTopics();let posts=0,replies=0,reactions=0,views=0;const activity=[];topics.forEach(t=>{if(String(t.author).toLowerCase()===key){posts++;views+=Number(t.views||0);activity.push({type:'Topic',title:t.title,date:t.date||'Recent',id:t.id})}(t.replies||[]).forEach(r=>{if(String(r.author).toLowerCase()===key){replies++;reactions+=Number(r.reaction||0);activity.push({type:'Reply',title:t.title,date:r.createdAt?new Date(r.createdAt).toLocaleDateString():'Recent',id:t.id})}})});return{posts,replies,reactions,views,total:posts+replies,activity:activity.slice(-12).reverse()}}
function safeUrl(url){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function reputationFor(n){if(n>=100)return{label:'Legendary',level:5};if(n>=50)return{label:'Trusted',level:4};if(n>=20)return{label:'Respected',level:3};if(n>=5)return{label:'Known',level:2};return{label:'Newcomer',level:1}}
function isOnline(name){try{const seen=JSON.parse(localStorage.getItem('ac_online_users')||'{}');return Date.now()-Number(seen[String(name).toLowerCase()]||0)<300000}catch{return false}}
function achievementList(user,stats,p){return window.AetherAchievements?AetherAchievements.evaluate(user,p):[]}
function socialLinks(user,p){const rows=[['🌐','Website',p.website],['🧱','Planet Minecraft',p.planetMinecraft],['▶️','YouTube',p.youtube],['💬','Discord',p.discordLink],['🟣','Twitch',p.twitch],['⌨️','GitHub',p.github]];return rows.filter(r=>safeUrl(r[2])).map(([icon,label,url])=>`<a href="${escapeHtml(safeUrl(url))}" target="_blank" rel="noopener"><span>${icon}</span><strong>${label}</strong><small>Open profile</small></a>`).join('')||'<p class="muted">No public links added yet.</p>'}
document.addEventListener('DOMContentLoaded',()=>{if(!document.querySelector('#publicProfilePage'))return;const requested=new URLSearchParams(location.search).get('user')||state.user?.username||'Admin',user=findCommunityUser(requested),p=profileDefaults(user),stats=calculateProfileStats(user.username),rep=reputationFor(stats.reactions),online=isOnline(user.username),avatar=$('#publicProfileAvatar');document.title=`${user.username} | AetherCraft`;$('#publicProfileName').textContent=user.username;$('#publicProfileDisplayName').textContent=p.profileName&&p.profileName!==user.username?p.profileName:'';$('#publicProfileStatus').textContent=`${user.role||'Member'} · ${p.status||'Community member'}`;$('#profileOnlineDot').classList.toggle('online',online);$('#publicMinecraftName').textContent=user.minecraft?.username?`Minecraft: ${user.minecraft.username}`:'Minecraft account not linked';avatar.src=p.profileImage||minecraftAvatar(user,180);avatar.onerror=()=>{avatar.onerror=null;avatar.src='https://mc-heads.net/avatar/MHF_Steve/180'};$('#profileReputation').textContent=`⭐ ${rep.label}`;$('#profileReactionTotal').textContent=`${stats.reactions} reactions · Level ${rep.level}`;$('#publicProfileBio').textContent=p.bio||'This member has not written a profile bio yet.';
const badges=[];if(['Founder','Administrator','Moderator','Builder','Veteran','Donator'].includes(user.role))badges.push(user.role);if(stats.posts>=10)badges.push('Contributor');if(stats.reactions>=25)badges.push('Popular');if((p.gallery||[]).length>=5)badges.push('Master Builder');if(user.minecraft?.username)badges.push('Minecraft Linked');$('#publicBadgeRow').innerHTML=(badges.length?badges:['Community Member']).map(b=>`<span>${escapeHtml(b)}</span>`).join('');
$('#publicProfileDetails').innerHTML=`<div><span>Forum username</span><strong>${escapeHtml(user.username)}</strong></div><div><span>Profile name</span><strong>${escapeHtml(p.profileName||user.username)}</strong></div><div><span>Joined</span><strong>${escapeHtml(user.joined||'Unknown')}</strong></div><div><span>Location</span><strong>${escapeHtml(p.location||'Not shared')}</strong></div><div><span>Favorite mode</span><strong>${escapeHtml(p.favoriteMode||'Not selected')}</strong></div><div><span>Minecraft username</span><strong>${escapeHtml(user.minecraft?.username||'Not linked')}</strong></div>`;
$('#publicProfileLinks').innerHTML=socialLinks(user,p);$('#publicProfileStats').innerHTML=`<div><strong>${stats.posts}</strong><span>Topics</span></div><div><strong>${stats.replies}</strong><span>Replies</span></div><div><strong>${stats.reactions}</strong><span>Reactions</span></div><div><strong>${stats.views}</strong><span>Topic views</span></div><div><strong>${stats.total}</strong><span>Total activity</span></div><div><strong>${(p.gallery||[]).length}</strong><span>Gallery builds</span></div>`;
$('#publicProfileActivity').innerHTML=stats.activity.length?stats.activity.map(a=>`<button class="member-activity-row" type="button" data-topic="${a.id}"><span>${a.type==='Topic'?'📝':'💬'}</span><div><strong>${escapeHtml(a.title)}</strong><small>${escapeHtml(a.type)} · ${escapeHtml(a.date)}</small></div><b>Open</b></button>`).join(''):'<p class="muted">No forum activity yet.</p>';$$('[data-topic]').forEach(b=>b.onclick=()=>location.href=`forums.html?topic=${b.dataset.topic}`);
const gallery=Array.isArray(p.gallery)?p.gallery:[];$('#galleryCount').textContent=`${gallery.length} BUILD${gallery.length===1?'':'S'}`;$('#publicProfileGallery').innerHTML=gallery.length?gallery.map((g,i)=>`<figure class="member-gallery-item" tabindex="0"><img src="${g.image}" alt="${escapeHtml(g.title||`Build ${i+1}`)}"><figcaption><strong>${escapeHtml(g.title||`Minecraft Build ${i+1}`)}</strong><span>${escapeHtml(g.description||'Community build showcase')}</span></figcaption></figure>`).join(''):'<div class="member-empty-gallery"><span>🧱</span><h3>No builds uploaded yet</h3><p>This member has not added anything to their gallery.</p></div>';
const achievements=achievementList(user,stats,p);$('#publicAchievements').innerHTML=achievements.map(a=>`<article class="member-achievement ${a.earned?'earned':'locked'}"><span>${a.earned?a.icon:'🔒'}</span><div><strong>${a.name}</strong><p>${a.desc}</p></div><b>${a.earned?'Earned':`${Math.min(a.current,a.goal)} / ${a.goal}`}</b></article>`).join('');
const sig=$('#publicSignature'),sigCard=$('#publicSignatureCard');if(p.signatureText||p.signatureImage)sig.innerHTML=`${p.signatureText?`<p>${escapeHtml(p.signatureText)}</p>`:''}${p.signatureImage?`<img src="${p.signatureImage}" alt="${escapeHtml(user.username)} signature">`:''}`;else sigCard.classList.add('hidden');if(state.user&&String(state.user.username).toLowerCase()===String(user.username).toLowerCase())$('#editOwnProfile').classList.remove('hidden');
$$('[data-profile-tab]').forEach(btn=>btn.onclick=()=>{$$('[data-profile-tab]').forEach(x=>x.classList.toggle('active',x===btn));$$('[data-profile-panel]').forEach(x=>x.classList.toggle('active',x.dataset.profilePanel===btn.dataset.profileTab))});
});