const defaultStaff=[
 {username:'Notch',role:'Owner',description:'Leads the server vision and community.'},
 {username:'Dinnerbone',role:'Developer',description:'Builds systems, plugins, and new features.'},
 {username:'jeb_',role:'Administrator',description:'Manages staff and player experience.'},
 {username:'Steve',role:'Moderator',description:'Helps players and keeps chat welcoming.'}
];
let staffMembers=(()=>{try{return JSON.parse(localStorage.getItem('ac_staff')||'null')||defaultStaff}catch{return defaultStaff}})();
const isStaffAdmin=()=>{try{return JSON.parse(localStorage.getItem('ac_user')||'null')?.role==='Administrator'}catch{return false}};
function saveStaff(){localStorage.setItem('ac_staff',JSON.stringify(staffMembers))}
function headUrl(name){return `https://mc-heads.net/avatar/${encodeURIComponent((name||'Steve').trim()||'Steve')}/110`}
function renderStaff(){const grid=document.getElementById('staffGrid'),admin=isStaffAdmin();document.getElementById('staffEditorNotice')?.classList.toggle('hidden',!admin);grid.innerHTML=staffMembers.map((m,i)=>`<article class="card staff-card" data-staff-index="${i}"><img class="staff-head" src="${headUrl(m.username)}" alt="${escapeHtml(m.username)}" loading="lazy"><span class="tag green staff-role-label">${escapeHtml(m.role)}</span><h3 class="staff-name">${escapeHtml(m.username)}</h3><p class="staff-description">${escapeHtml(m.description)}</p>${admin?`<div class="staff-edit"><div class="field"><label>Minecraft username</label><input class="input staff-username-input" value="${escapeHtml(m.username)}" maxlength="16" autocomplete="off"></div><div class="field"><label>Role</label><input class="input staff-role-input" value="${escapeHtml(m.role)}"></div><div class="field"><label>Description</label><textarea class="textarea staff-description-input">${escapeHtml(m.description)}</textarea></div><button class="btn danger staff-remove" type="button">Remove</button></div>`:''}</article>`).join('')+(admin?'<button id="addStaff" class="card add-staff-card" type="button"><strong>＋ Add staff member</strong><span class="muted">Create another synchronized Minecraft staff card.</span></button>':'');if(admin)bindStaffEditor()}
function bindStaffEditor(){document.querySelectorAll('.staff-card').forEach(card=>{const i=Number(card.dataset.staffIndex),name=card.querySelector('.staff-username-input'),role=card.querySelector('.staff-role-input'),desc=card.querySelector('.staff-description-input'),head=card.querySelector('.staff-head'),title=card.querySelector('.staff-name'),roleLabel=card.querySelector('.staff-role-label'),descText=card.querySelector('.staff-description');let timer;name.addEventListener('input',()=>{const value=name.value.trim()||'Steve';staffMembers[i].username=value;title.textContent=value;head.alt=value;clearTimeout(timer);timer=setTimeout(()=>head.src=headUrl(value),280);saveStaff();toast(`Staff username synced to ${value}`)});role.addEventListener('input',()=>{staffMembers[i].role=role.value;roleLabel.textContent=role.value||'Staff';saveStaff()});desc.addEventListener('input',()=>{staffMembers[i].description=desc.value;descText.textContent=desc.value;saveStaff()});card.querySelector('.staff-remove').onclick=()=>{if(confirm('Remove this staff member?')){staffMembers.splice(i,1);saveStaff();renderStaff();toast('Staff member removed')}}});document.getElementById('addStaff').onclick=()=>{staffMembers.push({username:'Steve',role:'Helper',description:'Add a description for this staff member.'});saveStaff();renderStaff();toast('Staff member added')}}
document.addEventListener('DOMContentLoaded',renderStaff);
